title: Cookie Clicker Auto-Clicker
description: Advanced automation bot for Cookie Clicker on Steam
show_downloads: false

remote_theme: pages-themes/midnight@v0.1.1

plugins:
  - jekyll-remote-theme

markdown: GFM