title: Cookie Clicker Auto-Clicker
description: Advanced automation bot for Cookie Clicker on Steam
show_downloads: true

remote_theme: pages-themes/cayman@v0.1.1

plugins:
  - jekyll-remote-theme

markdown: GFM